import os
dir_path = os.path.dirname(os.path.realpath(__file__))

three_row_icon_wind_temp = {
    'forecast_location' : { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 10,
        'width': .6,
        'height': .1,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (0, 0),
        'relative': False,
        'max_lines': 1,
        'mode': 'L',
        'font': dir_path+'/../../fonts/Montserrat/Montserrat-SemiBold.ttf',
        'mode': 'L'
    },
    'time_updated_local': {
        'type': 'TextBlock',
        'image': None,
        'padding': 10,
        'width': .4,
        'height': .1,
        'hcenter': False,
        'vcenter': True,
        'align': 'right',
        'abs_coordinates': (None, 0),
        'relative': ['forecast_location', 'time_updated_local'],
        'max_lines': 2,
        'mode': 'L',
        'font': dir_path+'/../../fonts/Montserrat/Montserrat-Regular.ttf',
    },
    # row 0
    '000_forecast_time_local': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['000_forecast_time_local', 'forecast_location'],
        'max_lines': 2,
        'mode': 'L',        
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    },
    '000_data_next_1_hours_summary_symbol_code_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_forecast_time_local', 'forecast_location'],
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    },    
    '000_data_instant_details_wind_barb_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_next_1_hours_summary_symbol_code_image', 'forecast_location'],
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    },
    '000_data_instant_details_air_temperature': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_instant_details_wind_barb_image', 'forecast_location'],
        'max_lines': 1,
        'mode': 'L',        
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    },    
    
    # row 1
    '006_forecast_time_local': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': False,
        'vcenter': True,
        'inverse': False,
        'abs_coordinates': (0, None),
        'relative': ['006_forecast_time_local', '000_forecast_time_local'],
        'max_lines': 2,
        'mode': 'L',        
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    }, 
    '006_data_next_1_hours_summary_symbol_code_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_forecast_time_local', '000_data_next_1_hours_summary_symbol_code_image'],
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    },
    '006_data_instant_details_wind_barb_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_data_next_1_hours_summary_symbol_code_image', '000_data_instant_details_wind_barb_image'],
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    },
    '006_data_instant_details_air_temperature': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_data_instant_details_wind_barb_image', '000_data_instant_details_air_temperature'],
        'max_lines': 1,
        'mode': 'L',        
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L',
        'border_config': {'fill': 0, 'width': 3, 'sides': ['bottom']},
    },
    
    # row 2
    '012_forecast_time_local': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['012_forecast_time_local', '006_forecast_time_local'],
        'max_lines': 2,
        'mode': 'L',        
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L'
    }, 
    '012_data_next_1_hours_summary_symbol_code_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['012_forecast_time_local', '006_data_next_1_hours_summary_symbol_code_image'],
        'mode': 'L',        
    },
    '012_data_instant_details_wind_barb_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['012_data_next_1_hours_summary_symbol_code_image', '006_data_instant_details_wind_barb_image'],
        'mode': 'L'
    },
    '012_data_instant_details_air_temperature': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 10,
        'width': 1/4,
        'height': .3,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['012_data_instant_details_wind_barb_image', '006_data_instant_details_air_temperature'],
        'max_lines': 1,
        'mode': 'L',        
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L'
    },    
}

three_column_icon_wind_temp_precip = {
    'forecast_location' : { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1,
        'height': 3/32,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (0, 0),
        'relative': False,
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Montserrat/Montserrat-SemiBold.ttf',
        'mode': 'L'
    },
    # Column 0
    '000_data_next_1_hours_summary_symbol_code_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 9/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['000_data_next_1_hours_summary_symbol_code_image', 'forecast_location'],
        'mode': 'L'
    },
    '000_data_instant_details_wind_barb_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/6,
        'height': 6/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['000_data_instant_details_wind_barb_image', '000_data_next_1_hours_summary_symbol_code_image'],
        'mode': 'L'
    },
    '000_data_instant_details_wind_speed': {
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/6,
        'height': 6/32,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_instant_details_wind_barb_image', '000_data_next_1_hours_summary_symbol_code_image'],
        'max_lines': 2,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '000_data_instant_details_air_temperature': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 6/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['000_data_instant_details_air_temperature', '000_data_instant_details_wind_speed'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },

    '000_data_next_1_hours_details_precipitation_amount': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 5/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['000_data_next_1_hours_details_precipitation_amount', '000_data_instant_details_air_temperature'],
        'max_lines': 2,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '000_forecast_time_local': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 3/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['000_forecast_time_local', '000_data_next_1_hours_details_precipitation_amount'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L'
    },

    # Column 1
    '006_data_next_1_hours_summary_symbol_code_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 9/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_next_1_hours_summary_symbol_code_image', 'forecast_location'],
        'mode': 'L'
    },
    '006_data_instant_details_wind_barb_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/6,
        'height': 6/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_instant_details_wind_speed', '006_data_next_1_hours_summary_symbol_code_image'],
        'mode': 'L'
    },
    '006_data_instant_details_wind_speed': {
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/6,
        'height': 6/32,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_data_instant_details_wind_barb_image', '006_data_next_1_hours_summary_symbol_code_image'],
        'max_lines': 2,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '006_data_instant_details_air_temperature': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 6/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_instant_details_air_temperature', '006_data_instant_details_wind_speed'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },

    '000_data_next_6_hours_details_precipitation_amount': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 5/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_next_1_hours_details_precipitation_amount', '006_data_instant_details_air_temperature'],
        'max_lines': 2,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '006_forecast_time_local': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 3/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_forecast_time_local', '000_data_next_6_hours_details_precipitation_amount'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L'
    },    
    

    # Column 2
    '012_data_next_1_hours_summary_symbol_code_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 9/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_data_next_1_hours_summary_symbol_code_image', 'forecast_location'],
        'mode': 'L'
    },
    '012_data_instant_details_wind_barb_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/6,
        'height': 6/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_data_instant_details_wind_speed', '012_data_next_1_hours_summary_symbol_code_image'],
        'mode': 'L'
    },
    '012_data_instant_details_wind_speed': {
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/6,
        'height': 6/32,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['012_data_instant_details_wind_barb_image', '012_data_next_1_hours_summary_symbol_code_image'],
        'max_lines': 2,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '012_data_instant_details_air_temperature': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 6/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_data_instant_details_air_temperature', '012_data_instant_details_wind_speed'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },

    '011_data_next_1_hours_details_precipitation_amount': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 5/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_next_6_hours_details_precipitation_amount', '012_data_instant_details_air_temperature'],
        'max_lines': 2,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '012_forecast_time_local': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/3,
        'height': 3/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['006_forecast_time_local', '011_data_next_1_hours_details_precipitation_amount'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Bold.ttf',
        'mode': 'L'
    },    
}


two_column_icon_wind_temp_precip = {
    '000_data_next_1_hours_summary_symbol_code_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/2,
        'height': 15/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (0, 0),
        'mode': 'L'
    },
    '000_data_instant_details_wind_barb_image': { 
        'type': 'ImageBlock',
        'image': True,
        'inverse': False,
        'padding': 0,
        'width': 1/2,
        'height': 15/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['000_data_instant_details_wind_barb_image', '000_data_next_1_hours_summary_symbol_code_image'],
        'mode': 'L'
    },
    'forecast_location': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1,
        'height': 2/32,
        'hcenter': False,
        'vcenter': True,
        'abs_coordinates': (0, None),
        'relative': ['forecast_location', '000_data_instant_details_wind_barb_image'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Montserrat/Montserrat-SemiBold.ttf',
        'mode': 'L'
    },
    't_max': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/4,
        'height': 2/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, 0),
        'relative': ['000_data_next_1_hours_summary_symbol_code_image',  't_max'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    't_min': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/4,
        'height': 2/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, 0),
        'relative': ['t_max',  't_min'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '000_data_next_6_hours_details_air_temperature_min': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/4,
        'height': 8/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_next_1_hours_summary_symbol_code_image',  't_max'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '000_data_next_6_hours_details_air_temperature_max': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/4,
        'height': 8/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_next_6_hours_details_air_temperature_min',  't_max'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    't_precipitation': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/2,
        'height': 2/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_instant_details_wind_barb_image',  '000_data_next_6_hours_details_air_temperature_max'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
    '000_data_next_1_hours_details_precipitation_amount': { 
        'type': 'TextBlock',
        'image': None,
        'inverse': False,
        'padding': 0,
        'width': 1/2,
        'height': 8/32,
        'hcenter': True,
        'vcenter': True,
        'abs_coordinates': (None, None),
        'relative': ['000_data_instant_details_wind_barb_image',  't_precipitation'],
        'max_lines': 1,
        'font': dir_path+'/../../fonts/Economica/Economica-Regular.ttf',
        'mode': 'L'
    },
}

# default layout
layout = three_row_icon_wind_temp